name: wp-app-boilerplate
recipe: wordpress
config:
  php: '7.4'
  webroot: web/web
services:
  appserver:
    run:
      - sh /app/tools/build.sh
  node:
    type: node:14
    run:
      - sh /app/tools/build_node.sh
  mailhog:
    type: mailhog
    hogfrom:
      - appserver